/**
 * All UI showcase items: sidebar nav + routes.
 * Every slug must have a corresponding page at app/ui/[slug]/page.tsx
 * or be handled by a dynamic route.
 */
export const UI_SHOWCASE_ITEMS: { path: string; label: string }[] = [
  { path: "/ui/color", label: "Color" },
  { path: "/ui/space", label: "Space" },
  { path: "/ui/icons", label: "Icon" },
  { path: "/ui/typography", label: "Type" },
  { path: "/ui/styles", label: "Effects" },
  { path: "/ui/accordion", label: "Accordion" },
  { path: "/ui/alert", label: "Alert" },
  { path: "/ui/alert-dialog", label: "Alert Dialog" },
  { path: "/ui/aspect-ratio", label: "Aspect Ratio" },
  { path: "/ui/avatar", label: "Avatar" },
  { path: "/ui/badge", label: "Badge" },
  { path: "/ui/breadcrumb", label: "Breadcrumb" },
  { path: "/ui/button", label: "Button" },
  { path: "/ui/button-group", label: "Button Group" },
  { path: "/ui/calendar", label: "Calendar" },
  { path: "/ui/card", label: "Card" },
  { path: "/ui/carousel", label: "Carousel" },
  { path: "/ui/chart", label: "Chart" },
  { path: "/ui/checkbox", label: "Checkbox" },
  { path: "/ui/collapsible", label: "Collapsible" },
  { path: "/ui/combobox", label: "Combobox" },
  { path: "/ui/command", label: "Command" },
  { path: "/ui/context-menu", label: "Context Menu" },
  { path: "/ui/data-table", label: "Data Table" },
  { path: "/ui/date-picker", label: "Date Picker" },
  { path: "/ui/dialog", label: "Dialog" },
  { path: "/ui/direction", label: "Direction" },
  { path: "/ui/drawer", label: "Drawer" },
  { path: "/ui/dropdown-menu", label: "Dropdown Menu" },
  { path: "/ui/empty", label: "Empty" },
  { path: "/ui/field", label: "Field" },
  { path: "/ui/hover-card", label: "Hover Card" },
  { path: "/ui/input", label: "Input" },
  { path: "/ui/input-group", label: "Input Group" },
  { path: "/ui/input-otp", label: "Input OTP" },
  { path: "/ui/item", label: "Item" },
  { path: "/ui/kbd", label: "Kbd" },
  { path: "/ui/label", label: "Label" },
  { path: "/ui/menubar", label: "Menubar" },
  { path: "/ui/native-select", label: "Native Select" },
  { path: "/ui/navigation-menu", label: "Navigation Menu" },
  { path: "/ui/pagination", label: "Pagination" },
  { path: "/ui/popover", label: "Popover" },
  { path: "/ui/progress", label: "Progress" },
  { path: "/ui/radio-group", label: "Radio Group" },
  { path: "/ui/resizable", label: "Resizable" },
  { path: "/ui/scroll-area", label: "Scroll Area" },
  { path: "/ui/select", label: "Select" },
  { path: "/ui/separator", label: "Separator" },
  { path: "/ui/sheet", label: "Sheet" },
  { path: "/ui/sidebar", label: "Sidebar" },
  { path: "/ui/skeleton", label: "Skeleton" },
  { path: "/ui/slider", label: "Slider" },
  { path: "/ui/sonner", label: "Sonner" },
  { path: "/ui/spinner", label: "Spinner" },
  { path: "/ui/switch", label: "Switch" },
  { path: "/ui/table", label: "Table" },
  { path: "/ui/tabs", label: "Tabs" },
  { path: "/ui/textarea", label: "Textarea" },
  { path: "/ui/toast", label: "Toast" },
  { path: "/ui/toggle", label: "Toggle" },
  { path: "/ui/toggle-group", label: "Toggle Group" },
  { path: "/ui/tooltip", label: "Tooltip" },
]
